name: 'Set ENVIRONMENT env var'
description: 'Set ENVIRONMENT and other variables'
author: 'gbh-tech'
branding:
  icon: 'info'
  color: 'gray-dark'

outputs:
  environment:
    description: 'Target environment to use'
    value: ${{ steps.set-environment.outputs.environment }}

runs:
  using: "composite"
  steps:
    - name: Determine current environment using the current git ref
      shell: bash -leo pipefail {0}
      id: set-environment
      run: |
        set_env() { echo "$1" >> $GITHUB_ENV; }
        set_output() { echo "$1" >> $GITHUB_OUTPUT; }

        echo "Printing current environment variables for debugging purposes..."
        env | grep GITHUB_

        DEV_EVENTS=(push pull_request workflow_dispatch)
        DEFAULT_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
        CURRENT_REF=${GITHUB_REF##*/}

        echo "Identified default branch : ${DEFAULT_BRANCH}"
        echo "Current git reference : ${CURRENT_REF}"

        if [[ "$CURRENT_REF" =~ ^v([0-9].[0-9].[0-9])$ ]]; then
          set_env "ENVIRONMENT=production"
          set_output "environment=production"
        elif [[ "$CURRENT_REF" =~ ^v([0-9].[0-9].[0-9])(-uat.[0-9]{1,2})$ ]]; then
          set_env "ENVIRONMENT=uat"
          set_output "environment=uat"
        elif [[ "$CURRENT_REF" =~ "$DEFAULT_BRANCH" ]]; then
          set_env "ENVIRONMENT=stage"
          set_output "environment=stage"
        elif [[ "${DEV_EVENTS[*]}" =~ "$GITHUB_EVENT_NAME" ]]; then
          set_env "ENVIRONMENT=stage"
          set_output "environment=stage"
        else
          echo "Error:"
          echo "The tag created for this deployment does not match defined conventions."
          echo "Check the README's 'Releases and deployments' section for more details."
          exit 1
        fi
